name: 'ğŸŒ Terraform Automation'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  TF_VAR_rg_name: "NetworkWatcherRG"
  TF_VAR_subscription_id: ${{secrets.SUBSCRIPTION_ID}}
  ARM_SUBSCRIPTION_ID: ${{secrets.SUBSCRIPTION_ID}}
  ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
  ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
  ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: ğŸ§© HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.0

      # - name: ğŸ“‚ Change Directory to Terraform Files
      #   run: |
      #     cd terraformsfiles  
      #     ls -la  

      - name : ğŸ”‘ az login
        id : az-login
        run : az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID

      - name: ğŸ—ï¸ Terraform Init
        id: init
        run: |
          cd terraformsfiles  
          terraform init -input=false

      # - name: ğŸ“‹ Terraform Plan
      #   id: plan
      #   run: |
      #     cd terraformsfiles 
      #     terraform plan -out=tfplan -input=false

      # - name: âœ… Terraform Apply
      #   id: apply
      #   run: |
      #     cd terraformsfiles  
      #     terraform apply -input=false -auto-approve tfplan


      - name: âœ… Terraform destroy
        id: destroy
        run: |
          cd terraformsfiles  
          terraform destroy 