name: 'ğŸŒ Terraform Automation'

on:
  workflow_dispatch:

env:
  TF_VAR_rg_name: "NetworkWatcherRG"
  TF_VAR_subscription_id: ${{secrets.SUBSCRIPTION_ID}}


jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: ğŸ§© HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.0

      - name: ğŸ”‘ Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}     

      - name: ğŸ—ï¸ Terraform Init
        id: init
        run: |
          cd terraformsfiles  
          terraform init -input=false
 


      # - name: ğŸ“‹ Terraform Plan
      #   id: plan
      #   run: |
      #     cd terraformsfiles 
      #     terraform plan -out=tfplan -input=false

      # - name: âœ… Terraform Apply
      #   id: apply
      #   run: |
      #     cd terraformsfiles  
      #     terraform apply -input=false -auto-approve tfplan


